export const BUTTON_BACKGROUND_COLOR = "#17BA6B";
export const BACKGROUND_COLOR = "#E5E5E5";
export const YELLOW_BACKGROUND = "#FFC100";
export const DARK_GREEN_BACKGROUND = "#1D945B";
export const ACTION_BUTTON_COLOR = '#9b59b6';